/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERACIONES_H_RPCGEN
#define _OPERACIONES_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STR 256

struct operation_log {
	char username[MAX_STR];
	char operation[MAX_STR];
	char date_time[MAX_STR];
	char file_name[MAX_STR];
};
typedef struct operation_log operation_log;

#define RPC 99
#define RPCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_op_log 1
extern  enum clnt_stat send_op_log_1(struct operation_log , int *, CLIENT *);
extern  bool_t send_op_log_1_svc(struct operation_log , int *, struct svc_req *);
extern int rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_op_log 1
extern  enum clnt_stat send_op_log_1();
extern  bool_t send_op_log_1_svc();
extern int rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation_log (XDR *, operation_log*);

#else /* K&R C */
extern bool_t xdr_operation_log ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERACIONES_H_RPCGEN */
